[stable/22.03] build.lock: pin attrs
The attrs package is an indirect dependency currently not covered
by the build.lock.  Recently upstream has moved along and
introduced new dependencies currently not present in the
wheelhouse leading to install failures such as:

    Processing ./wheelhouse/attrs-23.1.0.tar.gz
      Installing build dependencies: started
      Installing build dependencies: finished with status 'error'
       error: subprocess-exited-with-error

       × pip subprocess to install build dependencies did not run successfully.
       │ exit code: 1
       ╰─> [3 lines of output]
           Looking in links: wheelhouse
           ERROR: Could not find a version that satisfies the requirement hatchling (from versions: none)
           ERROR: No matching distribution found for hatchling
           [end of output]

       note: This error originates from a subprocess, and is likely not a problem with pip.
     error: subprocess-exited-with-error

     × pip subprocess to install build dependencies did not run successfully.
     │ exit code: 1
     ╰─> See above for output.

Add `attrs` to the locked set.

Change-Id: I2d0f2f1e27fe77418ad87f5c4dfdb46c96926095