build.lock: bump setuptools-scm version.
    LookupError: setuptools-scm was unable to detect version for /tmp/PATH

Signed-off-by: Frode Nordahl <fnordahl@ubuntu.com>
(cherry picked from commit 64ef1ad9db7fe2e80c243e3415f02209151c813d)